// esbuild.config.js
const esbuild = require("esbuild");
const path = require("path");

const isWatch = process.argv.includes("--watch");

/** @type {import('esbuild').BuildOptions} */
const buildOptions = {
  entryPoints: ["src/index.ts"],
  bundle: true,
  outfile: "dist/bundle.js",
  platform: "neutral",      // GAS はブラウザでも Node でもない
  target: ["es2020"],
  format: "iife",           // GAS はグローバルスコープで動作する
  globalName: "__bundle__", // IIFE のグローバル名（実質不要だが esbuild の要件）
  treeShaking: true,
  minify: false,            // GAS デバッグのためミニファイ無効（本番時は true に変更可）
  sourcemap: false,
  banner: {
    // GAS の clasp が認識できるようにファイル先頭にコメントを挿入
    js: "/* Auto-generated by esbuild. Do not edit directly. */",
  },
  // GAS グローバル API をバンドルから除外
  external: [],
  // esbuild が ES module の `export` を出力しないようにフッターで上書き
  footer: {
    js: "",
  },
  plugins: [gasExportsPlugin()],
};

/**
 * GAS 用プラグイン:
 * esbuild の IIFE バンドル後に、GAS から呼び出せるよう
 * `global` スコープへ関数をエクスポートする。
 */
function gasExportsPlugin() {
  return {
    name: "gas-exports",
    setup(build) {
      build.onEnd(async () => {
        const fs = require("fs");
        const outfile = build.initialOptions.outfile;
        let content = fs.readFileSync(outfile, "utf8");

        // IIFE の末尾に GAS グローバル登録コードを追加
        const gasFooter = `
// --- GAS Global Exports ---
// src/index.ts でエクスポートされた関数を GAS のグローバルスコープに登録する
(function registerGasGlobals() {
  const exports = __bundle__;
  if (typeof exports !== "object") return;
  Object.keys(exports).forEach(function (key) {
    if (typeof exports[key] === "function") {
      // @ts-ignore
      this[key] = exports[key];
    }
  });
}).call(this);
`;
        content += gasFooter;
        fs.writeFileSync(outfile, content, "utf8");
        console.log(`✅ Build complete: ${path.resolve(outfile)}`);
      });
    },
  };
}

if (isWatch) {
  esbuild.context(buildOptions).then((ctx) => {
    ctx.watch();
    console.log("👀 Watching for changes...");
  });
} else {
  esbuild.build(buildOptions).catch(() => process.exit(1));
}
